/*******************************************************************************
  ENC28J60 Configure State Machine
  Company:
    Microchip Technology Inc.

  File Name:
    drv_enc28j60_configure_state.h
  Summary:

  Description:
*******************************************************************************/
// DOM-IGNORE-BEGIN
/*****************************************************************************
 Copyright (C) 2015-2018 Microchip Technology Inc. and its subsidiaries.

Microchip Technology Inc. and its subsidiaries.

Subject to your compliance with these terms, you may use Microchip software 
and any derivatives exclusively with Microchip products. It is your 
responsibility to comply with third party license terms applicable to your 
use of third party software (including open source software) that may 
accompany Microchip software.

THIS SOFTWARE IS SUPPLIED BY MICROCHIP "AS IS". NO WARRANTIES, WHETHER 
EXPRESS, IMPLIED OR STATUTORY, APPLY TO THIS SOFTWARE, INCLUDING ANY IMPLIED 
WARRANTIES OF NON-INFRINGEMENT, MERCHANTABILITY, AND FITNESS FOR A PARTICULAR 
PURPOSE.

IN NO EVENT WILL MICROCHIP BE LIABLE FOR ANY INDIRECT, SPECIAL, PUNITIVE, 
INCIDENTAL OR CONSEQUENTIAL LOSS, DAMAGE, COST OR EXPENSE OF ANY KIND 
WHATSOEVER RELATED TO THE SOFTWARE, HOWEVER CAUSED, EVEN IF MICROCHIP HAS 
BEEN ADVISED OF THE POSSIBILITY OR THE DAMAGES ARE FORESEEABLE. TO THE 
FULLEST EXTENT ALLOWED BY LAW, MICROCHIP'S TOTAL LIABILITY ON ALL CLAIMS IN 
ANY WAY RELATED TO THIS SOFTWARE WILL NOT EXCEED THE AMOUNT OF FEES, IF ANY, 
THAT YOU HAVE PAID DIRECTLY TO MICROCHIP FOR THIS SOFTWARE.
*****************************************************************************/

// DOM-IGNORE-END
#ifndef _DRV_ENC28J60_CONFIGURE_STATE_H_
#define _DRV_ENC28J60_CONFIGURE_STATE_H_

#include "system_config.h"


struct _DRV_ENC28J60_DriverInfo;

typedef enum
{
    DRV_ENC28J60_CS_SET_ERXST,
    DRV_ENC28J60_CS_WAIT_ERXST,
    DRV_ENC28J60_CS_SET_ERXRDPT,
    DRV_ENC28J60_CS_WAIT_ERXRDPT,
    DRV_ENC28J60_CS_SET_ERXND,
    DRV_ENC28J60_CS_WAIT_ERXND,

    DRV_ENC28J60_CS_SET_ETXST,
    DRV_ENC28J60_CS_WAIT_ETXST,
	DRV_ENC28J60_CS_SET_EWRPT,
    DRV_ENC28J60_CS_WAIT_EWRPT,

    DRV_ENC28J60_CS_SET_MACON1,
    DRV_ENC28J60_CS_WAIT_MACON1,
	DRV_ENC28J60_CS_SET_MACON3,
    DRV_ENC28J60_CS_WAIT_MACON3,
	DRV_ENC28J60_CS_SET_MABBIPG,
    DRV_ENC28J60_CS_WAIT_MABBIPG,
	DRV_ENC28J60_CS_SET_MACON4,
    DRV_ENC28J60_CS_WAIT_MACON4,

	DRV_ENC28J60_CS_SET_MACLCON2,
    DRV_ENC28J60_CS_WAIT_MACLCON2,
	DRV_ENC28J60_CS_SET_MAIPG,
    DRV_ENC28J60_CS_WAIT_MAIPG,
	DRV_ENC28J60_CS_SET_MAMXFL,	
    DRV_ENC28J60_CS_WAIT_MAMXFL,

    DRV_ENC28J60_CS_WRITE_MAADR5,
    DRV_ENC28J60_CS_WAIT_MAADR5,
    DRV_ENC28J60_CS_WRITE_MAADR3,
    DRV_ENC28J60_CS_WAIT_MAADR3,
    DRV_ENC28J60_CS_WRITE_MAADR1,
    DRV_ENC28J60_CS_WAIT_MAADR1,

	DRV_ENC28J60_CS_SET_ECOCON,
    DRV_ENC28J60_CS_WAIT_ECOCON,

	DRV_ENC28J60_CS_SET_PHCON2,
	DRV_ENC28J60_CS_WAIT_PHCON2,
	DRV_ENC28J60_CS_SET_PHLCON,
	DRV_ENC28J60_CS_WAIT_PHLCON,
	DRV_ENC28J60_CS_SET_PHCON1,
	DRV_ENC28J60_CS_WAIT_PHCON1,
	DRV_ENC28J60_CS_SET_PHIE,
	DRV_ENC28J60_CS_WAIT_PHIE,

    DRV_ENC28J60_CS_SET_EIE,
    DRV_ENC28J60_CS_WAIT_EIE,
    
    DRV_ENC28J60_CS_SET_ECON2,
    DRV_ENC28J60_CS_WAIT_ECON2,
    DRV_ENC28J60_CS_SET_ECON1,
    DRV_ENC28J60_CS_WAIT_ECON1,

    DRV_ENC28J60_CS_DONE,

}DRV_ENC28J60_CONFIGURE_STATES;


typedef struct _DRV_ENC28J60_CONFIGURE_STATE_INFO
{
    DRV_ENC28J60_CONFIGURE_STATES state;
    uintptr_t   op;

}DRV_ENC28J60_CONFIGURE_STATE_INFO;

int32_t DRV_ENC28J60_ConfigStateTask(struct _DRV_ENC28J60_DriverInfo * pDrvInst);
int32_t DRV_ENC28J60_ConfigStateEnter(struct _DRV_ENC28J60_DriverInfo * pDrvInst);
int32_t DRV_ENC28J60_ConfigStateExit(struct _DRV_ENC28J60_DriverInfo * pDrvInst);


#endif
