format_version: v1.0
type: UniqueComponent
attributes: {id: sys_debug}
children:
- type: Symbols
  children:
  - type: String
    attributes: {id: SYS_CONSOLE_DEVICE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: sys_debug, value: SYS_CONSOLE_0}
  - type: String
    attributes: {id: SYS_CONSOLE_INDEX}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: sys_debug, value: '0'}
- type: Attachments
  children:
  - type: DirectDependency
    attributes: {id: sys_debug_SYS_CONSOLE_dependency}
    children:
    - type: Attributes
      children:
      - type: String
        attributes: {id: targetComponentID}
        children:
        - {type: Value, value: sys_console_0}
      - type: String
        attributes: {id: targetAttachmentID}
        children:
        - {type: Value, value: sys_console}
- type: ElementPosition
  attributes: {x: '557', y: '402', id: sys_debug}
