package:
  format-version: "1.0.0"
  name: "net"
  version: "3.8.0"
  type: "api"
  status: "production"
  
  dependencies:
    - name: "core"
      type: "package"
      version: "3.10.1"
    - name: "csp"
      type: "package"
      version: "3.11.1"
    - name: "bsp"
      type: "package"
      version: "3.11.1"
    - name: "dev_packs"
      type: "package"
      version: "v3.11.1"
    - name: "crypto"
      type: "package"
      version: "v3.7.6"
    - name: "usb"
      type: "package"
      version: "v3.8.1"
    - name: "wolfssl"
      type: "package"
      version: "v4.7.0"
    - name: "wolfMQTT"
      type: "package"
      version: "v1.11.1"
    - name: "CMSIS-FreeRTOS"
      type: "package"
      version: "v10.3.1"
