package:
  format-version: "1.0.0"
  name: "net"
  version: "v3.14.0"
  type: "api"
  status: "production"
  
  dependencies:
    - name: "core"
      type: "package"
      version: "v3.15.1"
    - name: "csp"
      type: "package"
      version: "v3.22.0"
    - name: "bsp"
      type: "package"
      version: "v3.22.0"
    - name: "crypto"
      type: "package"
      version: "v3.8.2"
    - name: "wolfMQTT"
      type: "package"
      version: "v1.19.1"
    - name: "harmony-services"
      type: "package"
      version: "v1.5.0"
