package:
  format-version: "1.0.0"
  name: "net"
  version: "3.10.0"
  type: "api"
  status: "production"
  
  dependencies:
    - name: "core"
      type: "package"
      version: "v3.13.0"
    - name: "csp"
      type: "package"
      version: "v3.17.0"
    - name: "bsp"
      type: "package"
      version: "v3.16.0"
    - name: "dev_packs"
      type: "package"
      version: "v3.17.0"
    - name: "crypto"
      type: "package"
      version: "v3.8.0"
    - name: "usb"
      type: "package"
      version: "v3.11.0-E2"
    - name: "wolfssl"
      type: "package"
      version: "v5.4.0"
    - name: "wolfMQTT"
      type: "package"
      version: "v1.11.1"
    - name: "CMSIS-FreeRTOS"
      type: "package"
      version: "v10.5.1"
