package:
  format-version: "1.0.0"
  name: "net"
  version: "v3.11.1"
  type: "api"
  status: "production"
  
  dependencies:
    - name: "core"
      type: "package"
      version: "v3.13.3"
    - name: "csp"
      type: "package"
      version: "v3.18.4"
    - name: "bsp"
      type: "package"
      version: "v3.18.0"
    - name: "crypto"
      type: "package"
      version: "v3.8.1"
    - name: "usb"
      type: "package"
      version: "v3.12.0"
    - name: "wolfssl"
      type: "package"
      version: "v5.4.0"
    - name: "wolfMQTT"
      type: "package"
      version: "v1.11.1"
    - name: "CMSIS-FreeRTOS"
      type: "package"
      version: "v10.5.1"
