<#--
/*******************************************************************************
  ENCX24J600 Driver Freemarker Template File

  Company:
    Microchip Technology Inc.

  File Name:
    drv_ecnX24j600.h.ftl

  Summary:
    ENCX24J600 Driver Freemarker Template File

  Description:

*******************************************************************************/
-->

<#----------------------------------------------------------------------------
 Copyright (C) 2014-2018 Microchip Technology Inc. and its subsidiaries.

Microchip Technology Inc. and its subsidiaries.

Subject to your compliance with these terms, you may use Microchip software 
and any derivatives exclusively with Microchip products. It is your 
responsibility to comply with third party license terms applicable to your 
use of third party software (including open source software) that may 
accompany Microchip software.

THIS SOFTWARE IS SUPPLIED BY MICROCHIP "AS IS". NO WARRANTIES, WHETHER 
EXPRESS, IMPLIED OR STATUTORY, APPLY TO THIS SOFTWARE, INCLUDING ANY IMPLIED 
WARRANTIES OF NON-INFRINGEMENT, MERCHANTABILITY, AND FITNESS FOR A PARTICULAR 
PURPOSE.

IN NO EVENT WILL MICROCHIP BE LIABLE FOR ANY INDIRECT, SPECIAL, PUNITIVE, 
INCIDENTAL OR CONSEQUENTIAL LOSS, DAMAGE, COST OR EXPENSE OF ANY KIND 
WHATSOEVER RELATED TO THE SOFTWARE, HOWEVER CAUSED, EVEN IF MICROCHIP HAS 
BEEN ADVISED OF THE POSSIBILITY OR THE DAMAGES ARE FORESEEABLE. TO THE 
FULLEST EXTENT ALLOWED BY LAW, MICROCHIP'S TOTAL LIABILITY ON ALL CLAIMS IN 
ANY WAY RELATED TO THIS SOFTWARE WILL NOT EXCEED THE AMOUNT OF FEES, IF ANY, 
THAT YOU HAVE PAID DIRECTLY TO MICROCHIP FOR THIS SOFTWARE.
----------------------------------------------------------------------------->


<#if CONFIG_DRV_ENCX24J600_USE_DRIVER>
/*** ENCX24J600 Driver Configuration ***/
/*** Driver Compilation and static configuration options. ***/
#define TCPIP_IF_ENCX24J600
#define DRV_ENCX24J600_INSTANCES_NUMBER ${CONFIG_DRV_ENCX24J600_INSTANCES_NUMBER}
#define DRV_ENCX24J600_CLIENT_INSTANCES ${CONFIG_DRV_ENCX24J600_CLIENT_INSTANCES}
<#if CONFIG_DRV_ENCX24J600_IDX0>
#define DRV_ENCX24J600_MAC_TX_DESCRIPTORS_IDX0 ${CONFIG_DRV_ENCX24J600_MAC_TX_DESCRIPTORS_IDX0}
#define DRV_ENCX24J600_MAC_RX_DESCRIPTORS_IDX0 ${CONFIG_DRV_ENCX24J600_MAC_RX_DESCRIPTORS_IDX0}
#define DRV_ENCX24J600_MAX_RX_BUFFER_IDX0 ${CONFIG_DRV_ENCX24J600_MAX_RX_BUFFER_IDX0}
#define DRV_ENCX24J600_SPI_DRIVER_INDEX_IDX0 ${CONFIG_DRV_ENCX24J600_SPI_DRV_INDEX_IDX0}
#define DRV_ENCX24J600_SPI_BPS_IDX0 ${CONFIG_DRV_ENCX24J600_SPI_BPS_IDX0}
#define DRV_ENCX24J600_SPI_SS_PORT_MODULE_IDX0 ${CONFIG_DRV_ENCX24J600_SPI_SS_PORT_MODULE_IDX0}
#define DRV_ENCX24J600_SPI_SS_PORT_CHANNEL_IDX0 ${CONFIG_DRV_ENCX24J600_SPI_SS_PORT_CHANNEL_IDX0}
#define DRV_ENCX24J600_SPI_SS_PORT_PIN_IDX0 ${CONFIG_DRV_ENCX24J600_SPI_SS_PORT_PIN_IDX0}
#define DRV_ENCX24J600_RX_BUFFER_SIZE_IDX0 ${CONFIG_DRV_ENCX24J600_RX_BUFFER_SIZE_IDX0}
#define DRV_ENCX24J600_MAX_FRAME_SIZE_IDX0 ${CONFIG_DRV_ENCX24J600_MAX_FRAME_SIZE_IDX0}
<#if CONFIG_DRV_ENCX24J600_ETHERNET_TYPE_IDX0 == "100base-T">
#define DRV_ENCX24J600_ETHERNET_TYPE_IDX0 TCPIP_ETH_OPEN_100
<#elseif CONFIG_DRV_ENCX24J600_ETHERNET_TYPE_IDX0 == "10base-T">
#define DRV_ENCX24J600_ETHERNET_TYPE_IDX0 TCPIP_ETH_OPEN_10
<#else>
#define DRV_ENCX24J600_ETHERNET_TYPE_IDX0 TCPIP_ETH_OPEN_AUTO
</#if>
<#if CONFIG_DRV_ENCX24J600_DUPLEX_MODE_IDX0 == "Half Duplex">
#define DRV_ENCX24J600_DUPLEX_MODE_IDX0 TCPIP_ETH_OPEN_HDUPLEX
<#elseif CONFIG_DRV_ENCX24J600_DUPLEX_MODE_IDX0 == "Full Duplex">
#define DRV_ENCX24J600_DUPLEX_MODE_IDX0 TCPIP_ETH_OPEN_FDUPLEX
<#else>
#define DRV_ENCX24J600_DUPLEX_MODE_IDX0 TCPIP_ETH_OPEN_AUTO
</#if>

</#if>
</#if>
