export const groupComponentConstant = {
    ROOT_VIEW:"__ROOTVIEW",
  TCP_IP_STACK: "TCP/IP STACK",
  APPLICATION_LAYER: "APPLICATION LAYER",
  PRESENTATION_LAYER: "PRESENTATION LAYER",
  TRANSPORT_LAYER: "TRANSPORT LAYER",
  NETWORK_LAYER: "NETWORK LAYER",
  DATA_LINK_LAYER: "DATA LINK LAYER",
  BASIC_CONFIGURATION: "BASIC CONFIGURATION",
};
