#include "system/sys_time_h2_adapter.h"
#include "system/sys_int_h2_adapter.h"
#include "system/sys_clk_h2_adapter.h"
#include "system/sys_random_h2_adapter.h"
#include "system/sys_reset_h2_adapter.h"