#include "system/sys_time_h2_adapter.h"
#include "system/sys_int_h2_adapter.h"
#include "system/sys_clk_h2_adapter.h"
#include "system/sys_cmd_h2_adapter.h"
#include "system/sys_console_h2_adapter.h"
#include "system/sys_random_h2_adapter.h"