<#--
/*******************************************************************************
  IPv6 Freemarker Template File

  Company:
    Microchip Technology Inc.

  File Name:
    ipv6.h.ftl

  Summary:
    IPv6 Freemarker Template File

  Description:

*******************************************************************************/
-->

<#----------------------------------------------------------------------------
 Copyright (C) 2014-2018 Microchip Technology Inc. and its subsidiaries.

Microchip Technology Inc. and its subsidiaries.

Subject to your compliance with these terms, you may use Microchip software 
and any derivatives exclusively with Microchip products. It is your 
responsibility to comply with third party license terms applicable to your 
use of third party software (including open source software) that may 
accompany Microchip software.

THIS SOFTWARE IS SUPPLIED BY MICROCHIP "AS IS". NO WARRANTIES, WHETHER 
EXPRESS, IMPLIED OR STATUTORY, APPLY TO THIS SOFTWARE, INCLUDING ANY IMPLIED 
WARRANTIES OF NON-INFRINGEMENT, MERCHANTABILITY, AND FITNESS FOR A PARTICULAR 
PURPOSE.

IN NO EVENT WILL MICROCHIP BE LIABLE FOR ANY INDIRECT, SPECIAL, PUNITIVE, 
INCIDENTAL OR CONSEQUENTIAL LOSS, DAMAGE, COST OR EXPENSE OF ANY KIND 
WHATSOEVER RELATED TO THE SOFTWARE, HOWEVER CAUSED, EVEN IF MICROCHIP HAS 
BEEN ADVISED OF THE POSSIBILITY OR THE DAMAGES ARE FORESEEABLE. TO THE 
FULLEST EXTENT ALLOWED BY LAW, MICROCHIP'S TOTAL LIABILITY ON ALL CLAIMS IN 
ANY WAY RELATED TO THIS SOFTWARE WILL NOT EXCEED THE AMOUNT OF FEES, IF ANY, 
THAT YOU HAVE PAID DIRECTLY TO MICROCHIP FOR THIS SOFTWARE.
----------------------------------------------------------------------------->


<#if TCPIP_STACK_USE_IPV6 == true>
/*** IPv6 Configuration ***/
#define TCPIP_IPV6_DEFAULT_ALLOCATION_BLOCK_SIZE 		${TCPIP_IPV6_DEFAULT_ALLOCATION_BLOCK_SIZE}
#define TCPIP_IPV6_MINIMUM_LINK_MTU 					${TCPIP_IPV6_MINIMUM_LINK_MTU}
#define TCPIP_IPV6_DEFAULT_LINK_MTU 					${TCPIP_IPV6_DEFAULT_LINK_MTU}
#define TCPIP_IPV6_DEFAULT_CUR_HOP_LIMIT 				${TCPIP_IPV6_DEFAULT_CUR_HOP_LIMIT}
#define TCPIP_IPV6_DEFAULT_BASE_REACHABLE_TIME 			${TCPIP_IPV6_DEFAULT_BASE_REACHABLE_TIME}
#define TCPIP_IPV6_DEFAULT_RETRANSMIT_TIME 				${TCPIP_IPV6_DEFAULT_RETRANSMIT_TIME}
#define TCPIP_IPV6_QUEUE_NEIGHBOR_PACKET_LIMIT 			${TCPIP_IPV6_QUEUE_NEIGHBOR_PACKET_LIMIT}
#define TCPIP_IPV6_NEIGHBOR_CACHE_ENTRY_STALE_TIMEOUT 	${TCPIP_IPV6_NEIGHBOR_CACHE_ENTRY_STALE_TIMEOUT}
#define TCPIP_IPV6_QUEUE_MCAST_PACKET_LIMIT 			${TCPIP_IPV6_QUEUE_MCAST_PACKET_LIMIT}
#define TCPIP_IPV6_QUEUED_MCAST_PACKET_TIMEOUT 			${TCPIP_IPV6_QUEUED_MCAST_PACKET_TIMEOUT}
#define TCPIP_IPV6_TASK_PROCESS_RATE 					${TCPIP_IPV6_TASK_PROCESS_RATE}
#define TCPIP_IPV6_INIT_TASK_PROCESS_RATE 				${TCPIP_IPV6_INIT_TASK_PROCESS_RATE}
#define TCPIP_IPV6_ULA_NTP_ACCESS_TMO 					${TCPIP_IPV6_ULA_NTP_ACCESS_TMO}
#define TCPIP_IPV6_ULA_NTP_VALID_WINDOW 				${TCPIP_IPV6_ULA_NTP_VALID_WINDOW}
#define TCPIP_IPV6_FRAGMENT_PKT_TIMEOUT 				${TCPIP_IPV6_FRAGMENT_PKT_TIMEOUT}
#define TCPIP_IPV6_RX_FRAGMENTED_BUFFER_SIZE 			${TCPIP_IPV6_RX_FRAGMENTED_BUFFER_SIZE}

<#if TCPIP_STACK_USE_ICMPV6_SERVER == true>
#define TCPIP_STACK_USE_ICMPV6_SERVER
</#if>
<#if TCPIP_STACK_USE_ICMPV6_CLIENT == true>
#define TCPIP_STACK_USE_ICMPV6_CLIENT
<#if TCPIP_ICMPV6_CLIENT_USER_NOTIFICATION == true>
#define TCPIP_ICMPV6_CLIENT_USER_NOTIFICATION   true
<#else>
#define TCPIP_ICMPV6_CLIENT_USER_NOTIFICATION   false
</#if>
</#if>
</#if>
