<#--
/*******************************************************************************
  Zero Config Freemarker Template File

  Company:
    Microchip Technology Inc.

  File Name:
    zeroconf.h.ftl

  Summary:
    Berkeley Freemarker Template File

  Description:

*******************************************************************************/
-->

<#----------------------------------------------------------------------------
 Copyright (C) 2014-2018 Microchip Technology Inc. and its subsidiaries.

Microchip Technology Inc. and its subsidiaries.

Subject to your compliance with these terms, you may use Microchip software 
and any derivatives exclusively with Microchip products. It is your 
responsibility to comply with third party license terms applicable to your 
use of third party software (including open source software) that may 
accompany Microchip software.

THIS SOFTWARE IS SUPPLIED BY MICROCHIP "AS IS". NO WARRANTIES, WHETHER 
EXPRESS, IMPLIED OR STATUTORY, APPLY TO THIS SOFTWARE, INCLUDING ANY IMPLIED 
WARRANTIES OF NON-INFRINGEMENT, MERCHANTABILITY, AND FITNESS FOR A PARTICULAR 
PURPOSE.

IN NO EVENT WILL MICROCHIP BE LIABLE FOR ANY INDIRECT, SPECIAL, PUNITIVE, 
INCIDENTAL OR CONSEQUENTIAL LOSS, DAMAGE, COST OR EXPENSE OF ANY KIND 
WHATSOEVER RELATED TO THE SOFTWARE, HOWEVER CAUSED, EVEN IF MICROCHIP HAS 
BEEN ADVISED OF THE POSSIBILITY OR THE DAMAGES ARE FORESEEABLE. TO THE 
FULLEST EXTENT ALLOWED BY LAW, MICROCHIP'S TOTAL LIABILITY ON ALL CLAIMS IN 
ANY WAY RELATED TO THIS SOFTWARE WILL NOT EXCEED THE AMOUNT OF FEES, IF ANY, 
THAT YOU HAVE PAID DIRECTLY TO MICROCHIP FOR THIS SOFTWARE.
----------------------------------------------------------------------------->

<#if TCPIP_USE_LINK_ZERO_CONFIG == true>
#define TCPIP_STACK_USE_ZEROCONF_LINK_LOCAL
<#if TCPIP_ZC_INFO_ZCLL>
#define TCPIP_ZC_INFO_ZCLL
</#if>
<#if TCPIP_ZC_DEBUG_ZCLL>
#define TCPIP_ZC_DEBUG_ZCLL
</#if>
<#if TCPIP_ZC_WARN_ZCLL>
#define TCPIP_ZC_WARN_ZCLL
</#if>
#define TCPIP_ZC_LL_PROBE_WAIT ${TCPIP_ZC_LL_PROBE_WAIT}
#define TCPIP_ZC_LL_PROBE_MIN ${TCPIP_ZC_LL_PROBE_MIN}
#define TCPIP_ZC_LL_PROBE_MAX ${TCPIP_ZC_LL_PROBE_MAX}
#define TCPIP_ZC_LL_PROBE_NUM ${TCPIP_ZC_LL_PROBE_NUM}
#define TCPIP_ZC_LL_ANNOUNCE_WAIT ${TCPIP_ZC_LL_ANNOUNCE_WAIT}
#define TCPIP_ZC_LL_ANNOUNCE_NUM ${TCPIP_ZC_LL_ANNOUNCE_NUM}
#define TCPIP_ZC_LL_ANNOUNCE_INTERVAL ${TCPIP_ZC_LL_ANNOUNCE_INTERVAL}
#define TCPIP_ZC_LL_MAX_CONFLICTS ${TCPIP_ZC_LL_MAX_CONFLICTS}
#define TCPIP_ZC_LL_RATE_LIMIT_INTERVAL ${TCPIP_ZC_LL_RATE_LIMIT_INTERVAL}
#define TCPIP_ZC_LL_DEFEND_INTERVAL ${TCPIP_ZC_LL_DEFEND_INTERVAL}
#define TCPIP_ZC_LL_IPV4_LLBASE ${TCPIP_ZC_LL_IPV4_LLBASE}
#define TCPIP_ZC_LL_IPV4_LLBASE_MASK ${TCPIP_ZC_LL_IPV4_LLBASE_MASK}
#define TCPIP_ZC_LL_TASK_TICK_RATE ${TCPIP_ZC_LL_TASK_TICK_RATE}
	<#if TCPIP_USE_MULTI_CAST_DNS_ZERO_CONFIG == true>
#define TCPIP_STACK_USE_ZEROCONF_MDNS_SD
<#if TCPIP_ZC_INFO_MDNS>
#define TCPIP_ZC_INFO_MDNS
</#if>
<#if TCPIP_ZC_DEBUG_MDNS>
#define TCPIP_ZC_DEBUG_MDNS
</#if>
<#if TCPIP_ZC_WARN_MDNS>
#define TCPIP_ZC_WARN_MDNS
</#if>
#define TCPIP_ZC_MDNS_TASK_TICK_RATE ${TCPIP_ZC_MDNS_TASK_TICK_RATE}
#define TCPIP_ZC_MDNS_PORT ${TCPIP_ZC_MDNS_PORT}
#define TCPIP_ZC_MDNS_MAX_HOST_NAME_SIZE ${TCPIP_ZC_MDNS_MAX_HOST_NAME_SIZE}
#define TCPIP_ZC_MDNS_MAX_LABEL_SIZE ${TCPIP_ZC_MDNS_MAX_LABEL_SIZE}
#define TCPIP_ZC_MDNS_MAX_RR_NAME_SIZE ${TCPIP_ZC_MDNS_MAX_RR_NAME_SIZE}
#define TCPIP_ZC_MDNS_MAX_SRV_TYPE_SIZE ${TCPIP_ZC_MDNS_MAX_SRV_TYPE_SIZE}
#define TCPIP_ZC_MDNS_MAX_SRV_NAME_SIZE ${TCPIP_ZC_MDNS_MAX_SRV_NAME_SIZE}
#define TCPIP_ZC_MDNS_MAX_TXT_DATA_SIZE ${TCPIP_ZC_MDNS_MAX_TXT_DATA_SIZE}
#define TCPIP_ZC_MDNS_RESOURCE_RECORD_TTL_VAL ${TCPIP_ZC_MDNS_RESOURCE_RECORD_TTL_VAL}
#define TCPIP_ZC_MDNS_MAX_RR_NUM ${TCPIP_ZC_MDNS_MAX_RR_NUM}
#define TCPIP_ZC_MDNS_PROBE_WAIT ${TCPIP_ZC_MDNS_PROBE_WAIT}
#define TCPIP_ZC_MDNS_PROBE_INTERVAL ${TCPIP_ZC_MDNS_PROBE_INTERVAL}
#define TCPIP_ZC_MDNS_PROBE_NUM ${TCPIP_ZC_MDNS_PROBE_NUM}
#define TCPIP_ZC_MDNS_MAX_PROBE_CONFLICT_NUM ${TCPIP_ZC_MDNS_MAX_PROBE_CONFLICT_NUM}
#define TCPIP_ZC_MDNS_ANNOUNCE_NUM ${TCPIP_ZC_MDNS_ANNOUNCE_NUM}
#define TCPIP_ZC_MDNS_ANNOUNCE_INTERVAL ${TCPIP_ZC_MDNS_ANNOUNCE_INTERVAL}
#define TCPIP_ZC_MDNS_ANNOUNCE_WAIT ${TCPIP_ZC_MDNS_ANNOUNCE_WAIT}

	</#if>
</#if>
