format_version: v1.0
type: UniqueComponent
attributes: {id: tcpip_apps_config}
children:
- type: Symbols
  children:
  - type: Boolean
    attributes: {id: TCPIP_AUTOCONFIG_ENABLE_DHCP_CLIENT}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: 'true'}
  - type: Boolean
    attributes: {id: TCPIP_AUTOCONFIG_ENABLE_DNS_CLIENT}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: 'true'}
- type: ElementPosition
  attributes: {x: '20', y: '20', id: tcpip_apps_config}
