format_version: v1.0
type: UniqueComponent
attributes: {id: tcpip_transport_config}
children:
- type: Symbols
  children:
  - type: Boolean
    attributes: {id: TCPIP_AUTOCONFIG_ENABLE_TCP}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: 'true'}
  - type: Boolean
    attributes: {id: TCPIP_AUTOCONFIG_ENABLE_UDP}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: tcpip_apps_config, value: 'true'}
- type: ElementPosition
  attributes: {x: '20', y: '20', id: tcpip_transport_config}
